application: coe2043-team-18
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js
  mime_type: text/javascript

- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css

- url: /.*
  script: guestbook.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
